# Experiment 1: Introduction to Deep Learning Libraries — TensorFlow and PyTorch

**Course:** AML ZC417 – Introduction to Deep Learning
**Module Reference:** Module 3 — Data Representation and Deep Learning Frameworks
**Duration:** 2 hours

---

## Aim
To install/verify TensorFlow and PyTorch, understand tensors as the core data structure of deep learning, and compare the two frameworks by performing equivalent basic operations in each.

## Learning Outcomes
By the end of this experiment, you will be able to:
1. Explain what a tensor is and why frameworks are built around it.
2. Create, inspect, and manipulate tensors in **TensorFlow**.
3. Create, inspect, and manipulate tensors in **PyTorch**.
4. Perform basic arithmetic, reshaping, and indexing operations in both frameworks.
5. Check GPU availability and move tensors to GPU.
6. Articulate the key philosophical/API differences between TensorFlow and PyTorch.


## Part 0 — Environment Check

Run the cell below first. It confirms both libraries are installed and prints their versions.
If running on **Google Colab**, both libraries are pre-installed — you only need to run the check.


In [1]:
import sys
print("Python version:", sys.version)

import tensorflow as tf
print("TensorFlow version:", tf.__version__)

import torch
print("PyTorch version:", torch.__version__)


Python version: 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]
TensorFlow version: 2.21.0
PyTorch version: 2.13.0+cpu


**Checkpoint:** You should see three version numbers printed with no errors. If TensorFlow or PyTorch is missing, run:

```
!pip install tensorflow torch
```

in a new cell, then restart the runtime and re-run the check above.


---
## Part 1 — What Is a Tensor?

A **tensor** is a multi-dimensional array — the fundamental data structure every deep learning framework is built on.

| Rank | Name | Example |
|---|---|---|
| 0 | Scalar | a single number, e.g. `5.0` |
| 1 | Vector | `[1, 2, 3]` |
| 2 | Matrix | a 2D grid of numbers (e.g. a grayscale image) |
| 3 | 3D Tensor | e.g. an RGB image (height × width × channels) |
| 4+ | N-D Tensor | e.g. a batch of RGB images (batch × height × width × channels) |

Both TensorFlow and PyTorch represent all data — inputs, weights, activations, gradients — as tensors. Everything you do in deep learning eventually reduces to tensor operations.


---
## Part 2 — Tensors in TensorFlow

### 2.1 Creating Tensors


In [2]:
# Scalar, vector, matrix, and 3D tensor in TensorFlow
scalar_tf = tf.constant(7)
vector_tf = tf.constant([1, 2, 3])
matrix_tf = tf.constant([[1, 2], [3, 4]])
tensor3d_tf = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar_tf, "| rank:", tf.rank(scalar_tf).numpy())
print("Vector:", vector_tf, "| rank:", tf.rank(vector_tf).numpy())
print("Matrix:\n", matrix_tf, "| rank:", tf.rank(matrix_tf).numpy())
print("3D Tensor shape:", tensor3d_tf.shape, "| rank:", tf.rank(tensor3d_tf).numpy())


Scalar: tf.Tensor(7, shape=(), dtype=int32) | rank: 0
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32) | rank: 1
Matrix:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) | rank: 2
3D Tensor shape: (2, 2, 2) | rank: 3


### 2.2 Tensor Attributes

In [18]:
t = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Shape:", t.shape)
print("Data type:", t.dtype)
print("Number of dimensions:", t.ndim)
print("Total elements:", tf.size(t).numpy())


Shape: (2, 3)
Data type: <dtype: 'float32'>
Number of dimensions: 2
Total elements: 6


### 2.3 Basic Arithmetic Operations

In [4]:
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print("a + b =\n", a + b)
print("a - b =\n", a - b)
print("Element-wise multiply (a * b) =\n", a * b)
print("Matrix multiply (a @ b) =\n", a @ b)
print("Transpose of a =\n", tf.transpose(a))


a + b =
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
a - b =
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
Element-wise multiply (a * b) =
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Matrix multiply (a @ b) =
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Transpose of a =
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)


### 2.4 Reshaping and Indexing

In [19]:
x = tf.range(12)
print("Original:", x)

reshaped = tf.reshape(x, (3, 4))
print("Reshaped to (3,4):\n", reshaped)

print("First row:", reshaped[0])
print("Element at [1,2]:", reshaped[1, 2].numpy())
print("Last column:", reshaped[:, -1])


Original: tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
Reshaped to (3,4):
 tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]], shape=(3, 4), dtype=int32)
First row: tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
Element at [1,2]: 6
Last column: tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)


### 2.5 NumPy Interoperability

In [6]:
import numpy as np

np_array = np.array([[1, 2], [3, 4]])
tf_from_np = tf.constant(np_array)
print("TF tensor from NumPy:\n", tf_from_np)

back_to_np = tf_from_np.numpy()
print("Back to NumPy:\n", back_to_np, type(back_to_np))


TF tensor from NumPy:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)
Back to NumPy:
 [[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 2.6 GPU Check (TensorFlow)

In [21]:
print("GPU available (TensorFlow):", len(tf.config.list_physical_devices('GPU'))>0)
print("Devices:", tf.config.list_physical_devices())


GPU available (TensorFlow): False
Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


> **Note:** On Google Colab, enable a GPU via `Runtime > Change runtime type > Hardware accelerator > GPU` to see a GPU device listed above.


---
## Part 3 — Tensors in PyTorch

We now repeat the *same* operations in PyTorch so you can directly compare syntax and behaviour.

### 3.1 Creating Tensors


In [8]:
# Scalar, vector, matrix, and 3D tensor in PyTorch
scalar_pt = torch.tensor(7)
vector_pt = torch.tensor([1, 2, 3])
matrix_pt = torch.tensor([[1, 2], [3, 4]])
tensor3d_pt = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Scalar:", scalar_pt, "| rank:", scalar_pt.dim())
print("Vector:", vector_pt, "| rank:", vector_pt.dim())
print("Matrix:\n", matrix_pt, "| rank:", matrix_pt.dim())
print("3D Tensor shape:", tensor3d_pt.shape, "| rank:", tensor3d_pt.dim())


Scalar: tensor(7) | rank: 0
Vector: tensor([1, 2, 3]) | rank: 1
Matrix:
 tensor([[1, 2],
        [3, 4]]) | rank: 2
3D Tensor shape: torch.Size([2, 2, 2]) | rank: 3


### 3.2 Tensor Attributes

In [9]:
t = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Shape:", t.shape)
print("Data type:", t.dtype)
print("Number of dimensions:", t.ndim)
print("Total elements:", t.numel())


Shape: torch.Size([2, 3])
Data type: torch.float32
Number of dimensions: 2
Total elements: 6


### 3.3 Basic Arithmetic Operations

In [10]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print("a + b =\n", a + b)
print("a - b =\n", a - b)
print("Element-wise multiply (a * b) =\n", a * b)
print("Matrix multiply (a @ b) =\n", a @ b)
print("Transpose of a =\n", a.T)


a + b =
 tensor([[ 6.,  8.],
        [10., 12.]])
a - b =
 tensor([[-4., -4.],
        [-4., -4.]])
Element-wise multiply (a * b) =
 tensor([[ 5., 12.],
        [21., 32.]])
Matrix multiply (a @ b) =
 tensor([[19., 22.],
        [43., 50.]])
Transpose of a =
 tensor([[1., 3.],
        [2., 4.]])


### 3.4 Reshaping and Indexing

In [24]:
x = torch.arange(12)
print("Original:", x)

reshaped = x.reshape(3, 4)
print("Reshaped to (3,4):\n", reshaped)

print("First row:", reshaped[0])
print("Element at [1,2]:", reshaped[1, 2].item())
print("Last column:", reshaped[:, -1])


Original: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Reshaped to (3,4):
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
First row: tensor([0, 1, 2, 3])
Element at [1,2]: 6
Last column: tensor([ 3,  7, 11])


### 3.5 NumPy Interoperability

In [12]:
np_array = np.array([[1, 2], [3, 4]])
pt_from_np = torch.from_numpy(np_array)
print("PyTorch tensor from NumPy:\n", pt_from_np)

back_to_np = pt_from_np.numpy()
print("Back to NumPy:\n", back_to_np, type(back_to_np))


PyTorch tensor from NumPy:
 tensor([[1, 2],
        [3, 4]])
Back to NumPy:
 [[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 3.6 GPU Check (PyTorch)

In [13]:
print("GPU available (PyTorch):", torch.cuda.is_available())
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# Moving a tensor to the selected device
sample = torch.tensor([1.0, 2.0, 3.0]).to(device)
print("Tensor is on:", sample.device)


GPU available (PyTorch): False
Using device: cpu
Tensor is on: cpu


In [ ]:
%%sql


---
## Part 4 — Side-by-Side Comparison

| Operation | TensorFlow | PyTorch |
|---|---|---|
| Create tensor | `tf.constant([1,2,3])` | `torch.tensor([1,2,3])` |
| Shape | `.shape` | `.shape` |
| Rank/ndim | `tf.rank(x)` or `.ndim` | `.dim()` or `.ndim` |
| Reshape | `tf.reshape(x, (3,4))` | `x.reshape(3,4)` |
| Matrix multiply | `a @ b` or `tf.matmul(a,b)` | `a @ b` or `torch.matmul(a,b)` |
| To NumPy | `.numpy()` | `.numpy()` |
| From NumPy | `tf.constant(np_array)` | `torch.from_numpy(np_array)` |
| GPU check | `tf.config.list_physical_devices('GPU')` | `torch.cuda.is_available()` |
| Execution style | Eager by default (TF2.x); can build static graphs via `tf.function` | Eager (define-by-run) by default |
| Typical use | Production deployment, TensorFlow Serving/Lite, industry pipelines | Research, rapid prototyping, most recent papers |

### Key takeaway
Both frameworks are built around the same core idea — **tensors + automatic differentiation** — but differ in API style and ecosystem. Neither is "better"; the choice depends on the project's deployment needs, team familiarity, and community/library support.


---
## Part 5 — In-Lab Exercise (to be completed and shown to the instructor)

Complete the following in the empty cells below:

1. Create a **4×4 tensor** of random integers between 0 and 10 in **both** TensorFlow and PyTorch.
2. Compute its **sum**, **mean**, and **maximum value** in both frameworks.
3. Reshape it into an **8×2** tensor in both frameworks.
4. In one or two sentences (in a markdown cell), state **one similarity** and **one difference** you noticed between the two frameworks' syntax.


In [14]:
# TODO 1 & 2: TensorFlow — random 4x4 tensor, sum, mean, max
# your code here


In [15]:
# TODO 1 & 2: PyTorch — random 4x4 tensor, sum, mean, max
# your code here


In [16]:
# TODO 3: Reshape both tensors to 8x2
# your code here
